package it.sh.prob.mas.utilites;

public class SHACLProtocolID {

	public static final String USER_REQUEST= "USER_REQUEST";
	public static final String REASONING_REQUEST_FROM_NEGOTIATOR_TO_REASONER= "REASONING_REQUEST_FROM_NEGOTIATOR_TO_REASONER";
	public static final String REASONING_RESULT_FROM_REASONER_TO_NEGOTIATOR = "REASONING_RESULT_FROM_REASONER_TO_NEGOTIATOR";
	public static final String REASONING_REQUEST_FROM_REASONER_TO_NEGOTIATOR= "REASONING_REQUEST_FROM_REASONER_TO_NEGOTIATOR";
	public static final String REASONING_REQUEST_FROM_NEGOTIATIOR_TO_NEGOTITATOR = "REASONING_REQUEST_FROM_NEGOTIATIOR_TO_NEGOTITATOR";
	public static final String REASONING_RESULT_FROM_NEGOTIATIOR_TO_NEGOTITATOR = "REASONING_RESULT_FROM_NEGOTIATIOR_TO_NEGOTITATOR";
	public static final String REASONING_RESULT_FROM_NEGOTIATIOR_TO_NEGOTIATOR = "REASONING_RESULT_FROM_NEGOTIATIOR_TO_NEGOTIATOR";
	
		public static final String MISSINGDATA_REQUEST_FROM_REASONER_TO_NEGOTIATOR = "MISSINGDATA_REQUEST_FROM_REASONER_TO_NEGOTIATOR";
	public static final String MISSINGDATA_REFUSE_FROM_NEGOTIATOR_TO_NEGOTIATOR= "MISSINGDATA_REFUSE_FROM_NEGOTIATOR_TO_NEGOTIATOR";

	
		public static final String MISSINGDATA_REQUEST_NEGOTIATOR_TO_NEGOTIATOR= "MISSINGDATA_REQUEST_NEGOTIATOR_TO_NEGOTIATOR";
	public static final String MISSINGDATA_REQUEST_NEGOTIATOR_TO_DEVICE= "MISSINGDATA_REQUEST_NEGOTIATOR_TO_DEVICE";
	public static final String MISSINGDATA_INFORM_DEVICE_TO_NEGOTIATOR= "MISSINGDATA_INFORM_DEVICE_TO_NEGOTIATOR";
	public static final String MISSINGDATA_INFORM_NEGOTIATOR_TO_NEGOTIATOR = "MISSINGDATA_INFORM_NEGOTIATOR_TO_NEGOTIATOR";
	public static final String MISSINGDATA_FAILURE_NEGOTIATOR_TO_REASOSNER= "MISSINGDATA_FAILURE_NEGOTIATOR_TO_REASOSNER";
	public static final String MISSINGDATA_INFORM_NEGOTIATOR_TO_REASONER = "MISSINGDATA_INFORM_NEGOTIATOR_TO_REASONER";
	
}
